version: "3.9"
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file: ./backend/.env
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    env_file: ./frontend/.env
    depends_on:
      - backend
volumes:
  pgdata:
